### ISSUE TITLE
possible bug in measure_word function

### ISSUE THREAD

**Issue by LaurentLessard** [LaurentLessard/wordlesolver#5]
@vtjeng I think I might have made an error in `measure_word`. I don't think it handles all cases of repeated letters correctly. For example, I think that if the correct word is "STAGE" and you guess "SPASM", the code returns "20210". But in the actual Wordle game, it would return "20200", which signals that there is one "S" in the solution. These are rare occurrences since such scenarios don't come up very often... but if we are making histograms over all possible outcomes, I think it will definitely affect the results.

The best solution here would be to dig into the Wordle [source code](https://bert.org/assets/posts/wordle/main-beautified.js) to figure out exactly how word scoring is handled, but that might take some time.

Edit: I posted this as a question on Twitter and got this response: https://twitter.com/LaurentLessard/status/1480609143027388420
So it seems that `measure_word` does indeed need to be updated.

**Comment by vtjeng** [comment]
Phew! Thanks for finding the issue. I wasn't excited at the prospect of looking through minified Javascript.

https://gist.github.com/zwegner/508cc183ab94dd27686a40384783ca4e#file-anti_wordle-py-L15-L26 is an implementation that works in Python (we'd have to adjust it to output the 5-digit ternary mask we're using, rather than the 10-digit binary mask it produces).

**Comment by LaurentLessard** [comment]
I pushed an update that fixed the bug. Also recomputed the plots. This led to small changes in the results. The max-entropy heuristic now has a worst-case length of 6 for both word lists.
